name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches: [ "dev", "master" ]
#   pull_request:
#     branches: [ "dev", "master" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: registry-1.docker.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile  --no-cache --tag php83:$(date +%s)
#      run: sudo docker build --no-cache .
#   test:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - name: Test the Docker image
#         run: docker-compose up -d 
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            user/app:latest
            ${{ secrets.DOCKER_USERNAME }}/php83:${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}

#    steps:
#      - name: Check out the repo
#        uses: actions/checkout@v3
#
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v2
#
#      - name: Log in to Docker Hub
#        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#
#      - name: Extract metadata (tags, labels) for Docker
#        id: meta
#        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
#        with:
#          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
#
#      - name: Build and push Docker image
#        uses: docker/build-push-action@v5
#        with:
#          context: "{{defaultContext}}"
#          push: true
#          tags: ${{ secrets.DOCKER_USERNAME }}/php83:${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
#          labels: ${{ steps.meta.outputs.labels }}
